# PKG-17-2-loop.py -- the loop itself (PKG-17-1, sections 4 and 7)
#
# The question, frozen before any of this existed: if the content of the contract
# is not given from outside but generated by the finished state of the instances,
# does the system return to the perfectly flat network, collapse into pairs, or
# stay somewhere between?
#
# Nothing here decides anything the rulebook did not already fix. The four
# verdict classes, their thresholds, the family of six generating rules, the two
# normalisations, the four starters, the seed, the round count and the stopping
# tolerance all come from PKG-17-1, which is frozen and was committed on
# 2026-08-19, before this file existed. This script runs them and classifies.
#
# A separate blind prediction was registered before the run: JOS-03, seal
# 01535a4adc8f50b8, commit eb629eed of 2026-08-21T02:01:12+02:00. It is NOT the
# rulebook's -- PKG-17-1 deliberately made no prediction -- and it does not touch
# the rulebook's verdict rule. It is judged separately at the end.
#
# Usage:  python shared/II-17-contract-origin/PKG-17-2-loop.py

import sys
import time
from pathlib import Path

import numpy as np

SHARED = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SHARED))

from parallel.hurok_feladat import futas, PAROK, ZAJ                 # noqa: E402
from parallel.runner import Feladat, futtat, jelentes                # noqa: E402

CSALAD = ["F1", "F2", "F3", "F4", "F5", "F6"]
NORMALAS = ["N1", "N2"]
INDULO = ["I1", "I2", "I3", "I4"]

PAR_KUSZOB = 0.95            # PKG-17-1, section 7
URES_KUSZOB = 1e-12


def besorol(r):
    """The four classes of PKG-17-1, section 7, in the order the rulebook gives.

    ERTELMEZES, marked: the rulebook says FLAT means the spread stays 'below the
    starting noise'. For I1 that noise is explicit; for I2-I4 the starting spread
    comes from the raise instead. Taking the run's OWN starting spread as the
    reference is the reading that works for all four starters, and it is fixed
    here rather than chosen after seeing the numbers."""
    if r["vegso_max"] <= URES_KUSZOB:
        return "URES"
    if r["vegso_szoras"] < r["kezdo_szoras"]:
        return "LAPOS"
    if r["top6_arany"] >= PAR_KUSZOB:
        return "PAR"
    if r["megallt_kor"] is not None:
        return "KOZTES"
    return "NEM ALLT MEG"


def main():
    kezd = time.time()
    print("== PKG-17-2 -- a hurok ==")
    print("   rendszer: 12 objektum, mind a %d par, valtozo tartalmu kotes-szerzodes"
          % len(PAROK))
    print("   mezony  : %d futas (%d csaladtag x %d normalas x %d indulo), 200 kor"
          % (len(CSALAD) * len(NORMALAS) * len(INDULO),
             len(CSALAD), len(NORMALAS), len(INDULO)))
    print("   a JOS-03 vak joslat a futas ELOTT commitolva: eb629eed, 02:01:12")
    print()

    feladatok = [Feladat(azonosito="%s/%s/%s" % (c, n, i),
                         fuggveny="parallel.hurok_feladat:futas",
                         argumentumok={"csalad": c, "normalas": n, "indulo": i})
                 for c in CSALAD for n in NORMALAS for i in INDULO]

    eredmeny = futtat(feladatok, magok=8, rendproba=3, gyoker=str(SHARED),
                      cimke="hurok-futasok")
    if eredmeny.hibak:
        print("   %d futas elszallt -- allj meg." % len(eredmeny.hibak))
        return 1
    if eredmeny.rendproba and eredmeny.rendproba[1]:
        print("   RENDPROBA BUKIK -- allj meg.")
        return 1
    jelentes(eredmeny, cimke="a 48 futas")

    rek = {r["csalad"] + "/" + r["normalas"] + "/" + r["indulo"]: r
           for r in eredmeny.ertekek if r}
    oszt = {k: besorol(v) for k, v in rek.items()}

    # --- the table ----------------------------------------------------------
    print("== BESOROLAS (PKG-17-1, 7. szakasz) ==")
    print("   %-4s %-4s | %-9s %-9s %-9s %-9s" % ("", "", *INDULO))
    for c in CSALAD:
        for n in NORMALAS:
            sor = ["%-9s" % oszt.get("%s/%s/%s" % (c, n, i), "?") for i in INDULO]
            print("   %-4s %-4s | %s" % (c, n, " ".join(sor)))
    print()

    # --- the rulebook's own verdict -----------------------------------------
    print("== ITELET a PKG-17-1 7. szakasza szerint ==")
    i1 = {(c, n): oszt["%s/%s/I1" % (c, n)] for c in CSALAD for n in NORMALAS}
    koztes_mind = all(v == "KOZTES" for v in i1.values())
    egyseges = len(set(i1.values())) == 1
    nem_allt = [k for k, v in oszt.items() if v == "NEM ALLT MEG"]

    if nem_allt:
        print("   NEM ALL OSSZE ITELET: %d futas nem allt meg 200 koron belul." % len(nem_allt))
        print("      %s" % ", ".join(sorted(nem_allt)[:8]))
    if koztes_mind:
        print("   ALL A LEMMA: a KOZTES osztaly mind a hat csaladtagon es mindket")
        print("   normalason megjelenik az I1 indulobol.")
    elif egyseges:
        v = next(iter(i1.values()))
        print("   MEGBUKOTT A LEMMA: az I1-bol MINDEN csaladtag %s." % v)
    else:
        print("   RESZLEGES: a csaladtagok szetvalnak -- az eredmeny a generalo")
        print("   szabaly ALAKJARA erzekeny. A szabalykonyv 9. szakaszanak szavaval:")
        print("   az import nem szukult, csak egy szinttel beljebb koltozott.")
        for c in CSALAD:
            print("      %-3s N1=%-9s N2=%s" % (c, i1[(c, "N1")], i1[(c, "N2")]))
    print()

    # --- the registered questions -------------------------------------------
    print("== A REGISZTRALT KERDESEK (PKG-17-1, 6. szakasz) ==")
    print("   K-b (fugg-e az indulotol): %s"
          % ("egy medence -- minden indulo ugyanoda fut"
             if all(len({oszt["%s/%s/%s" % (c, n, i)] for i in INDULO}) == 1
                    for c in CSALAD for n in NORMALAS)
             else "TOBB medence -- van csaladtag, ahol az indulo szamit"))
    print("   K-c (egyezik-e a hat tag es a ket normalas): %s"
          % ("igen" if egyseges else "NEM"))
    elt = [k for k in rek if oszt[k] != oszt[k.rsplit("/", 2)[0] + "/N1/" + k.split("/")[2]]]
    print("   normalas-fuggo futasok: %d" % len(elt))
    print("   F5 kulon jelentve (T1): %s"
          % ", ".join("%s/%s=%s" % (n, i, oszt["F5/%s/%s" % (n, i)])
                      for n in NORMALAS for i in INDULO))
    print()

    # --- JOS-03, judged separately ------------------------------------------
    print("== A JOS-03 vak joslat itelete (kulon, nem a szabalykonyve) ==")
    s1 = not egyseges
    f2 = {n: oszt["F2/%s/I1" % n] for n in NORMALAS}
    f3 = {n: oszt["F3/%s/I1" % n] for n in NORMALAS}
    s2 = any(f2[n] != f3[n] for n in NORMALAS)
    par_van = any(oszt["%s/%s/I1" % (c, n)] == "PAR"
                  for c in ("F1", "F2") for n in NORMALAS)
    print("   S1 (a hat tag NEM egyseges): %s" % ("ALL" if s1 else "BUKIK"))
    print("   S2 (F2 es F3 kulonbozo osztalyba fut): %s -- F2 %s, F3 %s"
          % ("ALL" if s2 else "BUKIK", f2, f3))
    print("   (masodlagos) F1 vagy F2 PAR-ba fut az I1-bol: %s"
          % ("igen" if par_van else "nem"))
    print()
    if s1 and s2:
        print("   A JOS-03 BEALLT.")
    else:
        print("   A JOS-03 MEGBUKOTT -- es ez a program szempontjabol a jobb hir.")
    print()
    print("   (%.1f s)" % (time.time() - kezd))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
